### ISSUE TITLE
Fail to update when foreign key is missing.

### ISSUE THREAD

**Issue by jonathan0405** [APCLab/appmate#1]
當Update個別資料時
須將non-nullable的foreign key一併提供Update
否則將出現400 response code.

**Comment by iblislin** [comment]
IIRC, update 時 是否為必填 由 models.py 裡面的 `blank=True` 決定

**Comment by tzing** [comment]
- 此問題來自上傳時request method被設為 `PUT` ，改用 `PATCH` 可以解決
- Client端 `cf1768f` 已解決
  
  see: https://github.com/APCLab/AppMateClient/releases/tag/v0.9.5
